//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class crate
    {
        public int idcrate { get; set; }
        public int idproduct { get; set; }
        public int iduser { get; set; }
        public int total { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
