//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.crate = new HashSet<crate>();
            this.order = new HashSet<order>();
            this.storage = new HashSet<storage>();
        }
    
        public int idproduct { get; set; }
        public string title { get; set; }
        public int producttypeid { get; set; }
        public string work_time { get; set; }
        public string effectsam { get; set; }
        public string caliber { get; set; }
        public string volleysam { get; set; }
        public string amount { get; set; }
        public decimal cost { get; set; }
        public string photo { get; set; }
        public string ProductWork
        {
            get
            {
                if (work_time != null && work_time != "")
                    return "Рабочее время: " + work_time + "секунд";
                else return "";
            }
        }
        public string Producteffect
        {
            get
            {
                if (effectsam != null && effectsam != "")
                    return "Количество эффектов:" + effectsam + "";
                else return "";
            }
        }
        public string Productcolibre
        {
            get
            {
                if (caliber != null && caliber != "")
                    return "Калибр: " + caliber + "";
                else return "";
            }
        }
        public string Productvol
        {
            get
            {
                if (volleysam != null && volleysam != "")
                    return "Количество залпов: " + volleysam + "";
                else return "";
            }
        }
        public string ImgPath
        {
            get
            {
                return "/Resource/" + this.photo + ".png";
            }

        }
        public int GetTotal
        {
            get;
            set;
        }
        public Visibility visibilityforedit
        {
            get
            {
                if (role.roleid == 1)
                {
                    return Visibility.Visible;
                }
                else 
                {
                    return Visibility.Hidden;
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crate> crate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
        public virtual productype productype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storage> storage { get; set; }
    }
}
