//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public int idstorage { get; set; }
        public Nullable<int> idproduct { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string amount { get; set; }
    
        public virtual product product { get; set; }
    }
}
